theme: minima
title: First Github page blog
author: trishanil01
email: trishanil01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Testing my Github page blog description. Let's see if this pops
  up in google search!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  trishanil01 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
